import { NotesProvider } from '@/context/notes-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Notes App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${inter.className} bg-gray-100 dark:bg-zinc-800 min-h-screen`}>
				<NotesProvider>{children}</NotesProvider>
			</body>
		</html>
	);
}
